name: keyboard_connection
description: Quickly and easily check if an external keyboard (or barcode scanner) is connected to the device.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ridewithvia.keyboard_connection
        pluginClass: KeyboardConnectionPlugin
      ios:
        pluginClass: KeyboardConnectionPlugin
